<a href="https://colab.research.google.com/github/leandrozanon/DL_Unicamp/blob/master/Ex2_Leandro_Zanon_Siqueira.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso Deep Learning - Exercício pré-curso NumPy

Este é um notebook Jupyter contendo exercícios de programação matricial utilizando o Python e biblioteca NumPy.
Estes exercícios servem para verificar os conhecimentos da linguagem Python para manipulação matricial com a biblioteca NumPy.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o NumPy e consultar documentação e tutoriais disponíveis na Internet.

### Python

Recomenda-se utilizar o Google Colab para fazer esses exercícios (https://colab.research.google.com/) pois o curso será oferecido nele. A vantagem do Colab é ser uma plataforma gratuito que permite o uso de GPU, fundamental para a realização dos exercícios de deep learning.


### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python.


Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

# Exercícios usando NumPy

Os seguintes exercícios devem usar apenas o pacote NumPy.
Não se deve utilizar nenhum outro pacote adicional.
O NumPy é o pacote que faz o Python apropriado para programação científica.
A programação eficiente de matrizes multidimensionais (arrays ou tensores) é
feita através do conceito de programação matricial que evita o uso de laços
e iterações nos elementos da matriz.

Existem vários exemplos de uso de NumPy no conjunto de
notebooks tutorias disponíveis no GitHub:
- https://github.com/robertoalotufo/ia898/blob/master/master/0_index.ipynb

## Preencha o seu nome

In [2]:
print('Meu nome é: Leandro Zanon Siqueira')

Meu nome é: Leandro Zanon Siqueira


In [3]:
import numpy as np

Veja como é possível criar um array unidimensional e depois reformatá-lo para ser acessado como array bidimensional:

In [4]:
array = np.arange(10)
print(array)
print(array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [5]:
A = np.arange(24).reshape(4, 6)
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


### Exercício: imprimindo rows, cols, dimensions, shape and datatype

In [6]:
# imprima o número de linhas de A
print(A.shape[0])
# imprima o número de colunas de A
print(A.shape[1])
# imprima o número de dimensões de A
print(A.ndim)
# imprima o shape de A:
print(A.shape)
# imprima o tipo de dados (dtype) dos elementos de A:
print(A.dtype)

4
6
2
(4, 6)
int64


### Reshape

In [202]:
# Seja o vetor unidimensional a:
a = np.array([1, 2, 3, 4])
print(a, a.shape)

[1 2 3 4] (4,)


### Exercício: Converta o vetor unidimensional a em uma matriz vetor coluna (4 linhas e 1 coluna) utilizando reshape

In [209]:
a = a.reshape(4,1)  # Escreva código aqui.
print(a, a.shape)

[[1]
 [2]
 [3]
 [4]] (4, 1)


## Exercício: Cópia por referência, cópia rasa e cópia profunda

Explique a diferença entre estes 3 tipos de cópias e dê um exemplo de cada uma.
O conceito aqui é em relação ao NumPy e não ao Python.
**Resposta**: cópia Rasa gera views e pode haver compartilhamento de memória das variáveis. Cópia profunda duplica schemas e conteúdo em outro endereço de memória. Cópia por referência funciona apenas como "um ponteiro (apontador)", mas o conteúdo e schema estão em um único endereço da memória.


In [217]:
# Indique para cada uma das expressões a seguir se a cópia é por referência, rasa ou profunda
x = a # cópia por referência
y = a[:2] # cópia rasa
z = a.reshape(4, 1) # cópia rasa
zz = a.copy() # cópia profunda


In [218]:
## Para auxiliar na resposta abaixo:
print(np.may_share_memory(a,z))
print(np.may_share_memory(a,y))
print(np.may_share_memory(a,zz))

True
True
False


In [219]:
# Explique o valor dos resultados:
z[0,0] = 5
print(a) #explique: como z foi gerado a partir de uma cópia rasa de a (reshape), as variáveis compartilham memória. 
y[1] = 6
print(a) # explique: como y foi gerado a partir de uma cópia rasa de a (slicing), as variáveis compartilham memória. 
zz[0] = 7
print(a) # explique: não altera nenhum elemento de a, pois zz é uma cópia profunda de a, portanto não compartilham memória

[[5]
 [2]
 [3]
 [4]]
[[5]
 [6]
 [3]
 [4]]
[[5]
 [6]
 [3]
 [4]]


## Operações aritméticas

In [220]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [221]:
B = A + 10
B

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

### Array binário (booleano)

#### Exercício: Crie uma matriz booleana C com True nos elementos de B menores que 18 (não utilize loop explícito)

In [14]:
print(B)
C = B < 18
print(C)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]
 [22 23 24 25 26 27]
 [28 29 30 31 32 33]]
[[ True  True  True  True  True  True]
 [ True  True False False False False]
 [False False False False False False]
 [False False False False False False]]


## Indexação booleana

### Exercício: explique o comando a seguir de indexação booleana

In [15]:
print(B < 18)
print(A)

[[ True  True  True  True  True  True]
 [ True  True False False False False]
 [False False False False False False]
 [False False False False False False]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [16]:
A[B < 18]

array([0, 1, 2, 3, 4, 5, 6, 7])

Explicação: esta indexação é um slicing selecionando apenas os elementos com True estabelecido na representação booleana. 

Veja um programa que cria matriz D_loop a partir da matriz B, porém trocando os elementos menores que 18 por seus valores negativos

In [17]:
D_loop = B.copy()
for row in np.arange(B.shape[0]):
    for col in np.arange(B.shape[1]):
        if B[row,col] < 18:
            D_loop[row,col] = - B[row,col]
print(D_loop)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


### Exercício: Substitua o programa acima por uma única linha sem loop, utilizando indexação booleana e evitando o uso de `where`

In [18]:
B[B < 18] = -B[B < 18] # << modifique aqui utilizando indexação booleana
D = B    
print(D)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


## Redução de eixo: soma

Operações matriciais de redução de eixo são muito úteis e importantes.
É um conceito importante da programação matricial.

Estude o exemplo a seguir:

In [19]:
print(A)
print(A.shape)
As = A.sum(axis=0)
print(As)
print(As.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[36 40 44 48 52 56]
(6,)


### Exercício: Explique o funcionamento da soma por redução de eixo. Qual foi a dimensão que desapareceu?

Resposta: A soma por redução de eixo é a soma dos elementos de determinada dimensão parametrizada pelo parâmetro 'axis'. O parâmetro definido em 'axis' é a dimensão que ocorre a soma, ou seja, agregando os elementos de tal forma que a dimensão "suma".
Neste caso a dimensão restante é a 2a dimensão, justamente a não explícita no parâmetro 'axis'. Esta interpretação é análoga para arrays de 3 dimensões.

In [20]:
# Estudando reshaping e soma por redução de eixo
print(A.reshape(2,3,4))
print(A.reshape(2,3,4).shape)
print(A.reshape(2,3,4).sum(axis=1))
print(A.reshape(2,3,4).sum(axis=1).shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[[12 15 18 21]
 [48 51 54 57]]
(2, 4)


### Exercício: calcule o valor médio do array A

In [21]:
print(A.mean())

11.5


### Exercício: calcule o valor médio das linhas de A:

In [214]:
np.array([0,1,2,3,4]).mean()

2.0

In [213]:
print(A.mean(axis=1))

[ 2.5  8.5 14.5 20.5]


## Broadcasting

### Exercício: O que significa o conceito de broadcasting em NumPy?

Resposta: É a tratativa de arrays de diferentes dimensões em operções algébricas. É como se "alongasse" o array de menor dimensão para possibilitar a operação. 

### Exercício: Usando o conceito de broadcast, mude o shape do vetor a para que o broadcast possa ocorrer quando fizermos G = A + a

In [50]:
print(A.shape)

(4, 6)


In [57]:
a = np.arange(4).reshape((4,1))
print(a.shape)
print(a)
G = A + a
print(G)

(4, 1)
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]


## Normalização entre 0 e 1

Seja a matriz $C$ que é a normalização da matriz $A$:
$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max} - A_{min}} $$

Em programação matricial, não se faz o loop em cada elemento da matriz,
mas sim, utiliza-se operações matriciais. Faça o exercício a seguir
sem utilizar laços explícitos:

### Exercício: Criar a matriz C que é a normalização de A, de modo que os valores de C estejam entre 0 e 1.


In [62]:
C = (A - A.min())/(A.max() - A.min())
print(C)

[[0.         0.04347826 0.08695652 0.13043478 0.17391304 0.2173913 ]
 [0.26086957 0.30434783 0.34782609 0.39130435 0.43478261 0.47826087]
 [0.52173913 0.56521739 0.60869565 0.65217391 0.69565217 0.73913043]
 [0.7826087  0.82608696 0.86956522 0.91304348 0.95652174 1.        ]]


### Exercício: Modificar o exercício anterior, porém agora faça a normalização para cada coluna de A de modo que as colunas da matriz D estejam entre os valores de 0 a 1. Dica: utilize o conceito de redução de eixo.


In [66]:
D = (A - A.min(axis=0))/(A.max(axis=0) - A.min(axis=0))
print(D)

[[0.         0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
 [1.         1.         1.         1.         1.         1.        ]]


### Exercício: Modificar o exercício anterior, porém agora faça a normalização para cada linha de A de modo que as colunas da matriz E estejam entre os valores de 0 a 1. Dica: utilize o conceito de redução de eixo, porém mantenha o mesmo número de eixos para poder fazer broadcast.

In [264]:
E = (A - A.min(axis=1, keepdims=True))/(A.max(axis=1, keepdims=True) - A.min(axis=1, keepdims=True))
print(E)

[[0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]]


## Fatiamento em arrays (slicing)

In [157]:
print(A)
print(A[1::2])
A[:,0::2]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])

In [142]:
# esta indexação é chamada fatiamento:
AA = A[:,1::2]
print(AA)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


### Exercício: Crie a matriz AB apenas com as linhas pares da matriz A, utilizando o conceito de fatiamento:


In [158]:
AB = A[:,0::2]
print(AB)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]


### Exercicío: Crie a matriz AC com mesmo shape da matriz A, porém com os elementos na ordem inversa, ou seja, trocando a ordem das linhas e das colunas.



Por exemplo, a matriz [[1, 2, 3], [4, 5, 6]] será transformada para [[6, 5, 4], [3, 2, 1]]

In [236]:
 test = np.array([[1, 2, 3], [4, 5, 6]])
 test[-1::-1,-1::-1]

array([[6, 5, 4],
       [3, 2, 1]])

In [237]:
AC = A[-1::-1,-1::-1]
print(AC)

[[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


## Produto matricial  (dot product)

### Exercício: Calcule a matriz E dada pelo produto matricial entre a matriz A e sua transposta: 
$$ E = A A^T $$

In [249]:
0*0 + 1*1 + 2*2 + 3*3 + 4*4 + 5*5

55

In [246]:
print(A)
print(A.T)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [239]:
E = np.dot(A,A.T) # modify your code here
print(E)

[[  55  145  235  325]
 [ 145  451  757 1063]
 [ 235  757 1279 1801]
 [ 325 1063 1801 2539]]


### Exercício: Descomente a linha e explique por que a operação de multiplicação dá erro.

In [250]:
Ee = A * A.T
Ee

ValueError: ignored

A operação acusa erro, pois o python tenta fazer operação por elemento e não operação matricial.

## Matrizes multidimensionais

Em deep learning, iremos utilizar matrizes multidimensionais
que são denominados como arrays no NumPy. PyTorch usa o nome de tensor para
suas matrizes multimensionais.

Matrizes de dimensões maior que 4 são de difícil intuição. A melhor forma de lidar
com elas é observando o seu *shape*.

### 3-D array

In [251]:
F = A.reshape(2, 3, 4)
print(F)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Indexação

Estude as seguintes indexações:

In [252]:
F1 = F[1]
print(F1)
F2 = F[1,0,:]
print(F2)
F3 = F[1,0,2]
print(F3)
F4 = F[1:2,0,2]
print(F4)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[12 13 14 15]
14
[14]


In [256]:
print(F1.shape)
print(F2.shape)
print(F3.shape)
print(F4.shape)

(3, 4)
(4,)
()
(1,)


### Exercício: Explique as dimensões de cada array:

F1: bidimensional (3 linhas e 4 colunas)

F2: unidimensional (4 linhas)

F3: adimensional, é um inteiro

F4: unidimensional (1 linha)

## Redução de eixo - aplicado a dois eixos simultâneos

Redução de eixo é quando a operação matricial resulta num array de menores dimensões.
Com essas operações, calcula-se estatística de colunas, linhas, etc.

### Exercício: Calcule o valor médio das matrizes F[0] e F[1], usando apenas um único comando F.mean(??)

In [261]:
F[0].mean(), F[1].mean()

(5.5, 17.5)

In [271]:
F.mean(axis=(1,2))

array([ 5.5, 17.5])

## Function - split - dados treino e validação

O exercício a seguir é para separar um conjunto de dados (dataset) em dois conjuntos, um
de treinamento e outro de validação.


Defina uma função que receba como entrada uma matriz, (dataset), onde cada linha é
referente a uma amostra e cada coluna referente a um atributo das amostras. O número total de
amostras é dado pelas linhas desta matriz.
Outro parâmetro de entrada é o fator de split `split_factor`, que é um número real entre 0 e 1. 
A saída da função são duas matrizes: amostras de treinamento e amostras de validação. 
A matriz de treinamento conterá o número de linhas dado por `split_factor` vezes o número de amostras.
A matriz de validação conterá o restante das amostras.

In [359]:
# Entrada, matriz contendo 10 amostras e 9 atributos
aa = np.arange(90).reshape(10,9)
print(aa)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [307]:
# Saída da função t,v = split(aa, 0.8)  # utilizado split_factor de 80%
t = np.arange(72).reshape(8,9)
print(t)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


In [274]:
v = np.arange(72,90).reshape(2,9)
print(v)

[[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [400]:
# Evite o uso de laço explícito
# Não utilize outras bibliotecas além do NumPy
def split(dados, split_factor):
    '''
    divide a matriz dados em dois conjuntos:
    matriz train: split_factor * n. de linhas de dados
    matriz val: (1-split_factor) * n. de linhas de dados
    parametros entrada:
        dados: matriz de entrada
        split_factor: entre 0. e 1. - fator de divisão em duas matrizes
    parametros de saída:
        train : matriz com as linhas iniciais de dados
        val: matriz com as linhas restantes
    '''
    ## Truncando números de linhas para garantir que numero de linhas de train e val somadas sejam equivalentes a número de linhas de dados
    ## na prática eu usaria a lib math e a funçao trunc, porém só foi pedido lib numpy
    train_sample_size = int( round(split_factor * aa.shape[0], 0) )
    val_sample_size = int( round((1 - split_factor) * aa.shape[0], 0) )

    train = dados[:train_sample_size,:]
    val = dados[-val_sample_size:,:]

    train, val

    dados
    return train, val

t,v = split(aa, 0.8)
print('t=\n', t)
print('v=\n', v)

t=
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]
v=
 [[70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]


### Exercício: Teste sua função com outros valores

In [405]:
# Código robusto a qualquer dimensão de array
aa = np.arange(100).reshape(10,10)
print(aa)

t,v = split(aa, 0.15)
print('t=\n', t)
print('v=\n', v)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
t=
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
v=
 [[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# Fim do Notebook